// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('vue-termui')['TuiBox']
    GongDePlus: typeof import('./src/components/GongDePlus.vue')['default']
    Newline: typeof import('vue-termui')['TuiNewline']
    Text: typeof import('vue-termui')['TuiText']
    WoodenFishIcon: typeof import('./src/components/WoodenFishIcon.vue')['default']
  }
}
